# Keeping these at the top for convenience
# Frequently Updated Properties
	mod_version = 0.12.2
	btwr_sl_version=0.62
	loader_version=0.17.3
	fabric_version=0.116.7+1.21.1
	bwt_version=2.0.1

# Less Frequently Updated
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	cloth_config_version=15.0.140
	mod_menu_version=11.0.3
	emi_version=1.1.12+1.21

# Group & Archives Name
	maven_group = org.tough_environment
	archives_base_name = tough-environment

# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Frequency-based template by ivangeevo ;)
# Good for projects that have fewer dependencies